// Mocked Github search result for repositories items, used for unit testing only
export const mockRawSearchResult = {
  total_count: 1054384,
  items: [
    {
      id: 10270250,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
      name: 'react',
      full_name: 'facebook/react',
      private: false,
      owner: {
        login: 'facebook',
        id: 69631,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
        avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/facebook',
        html_url: 'https://github.com/facebook',
        followers_url: 'https://api.github.com/users/facebook/followers',
        following_url: 'https://api.github.com/users/facebook/following{/other_user}',
        gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
        organizations_url: 'https://api.github.com/users/facebook/orgs',
        repos_url: 'https://api.github.com/users/facebook/repos',
        events_url: 'https://api.github.com/users/facebook/events{/privacy}',
        received_events_url: 'https://api.github.com/users/facebook/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/facebook/react',
      description:
        'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
      fork: false,
      url: 'https://api.github.com/repos/facebook/react',
      forks_url: 'https://api.github.com/repos/facebook/react/forks',
      keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/facebook/react/teams',
      hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
      issue_events_url: 'https://api.github.com/repos/facebook/react/issues/events{/number}',
      events_url: 'https://api.github.com/repos/facebook/react/events',
      assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
      branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
      tags_url: 'https://api.github.com/repos/facebook/react/tags',
      blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/facebook/react/languages',
      stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
      contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
      subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
      subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
      commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/facebook/react/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/facebook/react/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
      compare_url: 'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/facebook/react/merges',
      archive_url: 'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
      issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
      pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/facebook/react/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
      releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
      deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
      created_at: '2013-05-24T16:15:54Z',
      updated_at: '2020-06-21T20:34:56Z',
      pushed_at: '2020-06-21T08:51:55Z',
      git_url: 'git://github.com/facebook/react.git',
      ssh_url: 'git@github.com:facebook/react.git',
      clone_url: 'https://github.com/facebook/react.git',
      svn_url: 'https://github.com/facebook/react',
      homepage: 'https://reactjs.org',
      size: 154848,
      stargazers_count: 150831,
      watchers_count: 150831,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 29421,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 645,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 29421,
      open_issues: 645,
      watchers: 150831,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 29028775,
      node_id: 'MDEwOlJlcG9zaXRvcnkyOTAyODc3NQ==',
      name: 'react-native',
      full_name: 'facebook/react-native',
      private: false,
      owner: {
        login: 'facebook',
        id: 69631,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
        avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/facebook',
        html_url: 'https://github.com/facebook',
        followers_url: 'https://api.github.com/users/facebook/followers',
        following_url: 'https://api.github.com/users/facebook/following{/other_user}',
        gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
        organizations_url: 'https://api.github.com/users/facebook/orgs',
        repos_url: 'https://api.github.com/users/facebook/repos',
        events_url: 'https://api.github.com/users/facebook/events{/privacy}',
        received_events_url: 'https://api.github.com/users/facebook/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/facebook/react-native',
      description: 'A framework for building native apps with React.',
      fork: false,
      url: 'https://api.github.com/repos/facebook/react-native',
      forks_url: 'https://api.github.com/repos/facebook/react-native/forks',
      keys_url: 'https://api.github.com/repos/facebook/react-native/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/facebook/react-native/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/facebook/react-native/teams',
      hooks_url: 'https://api.github.com/repos/facebook/react-native/hooks',
      issue_events_url: 'https://api.github.com/repos/facebook/react-native/issues/events{/number}',
      events_url: 'https://api.github.com/repos/facebook/react-native/events',
      assignees_url: 'https://api.github.com/repos/facebook/react-native/assignees{/user}',
      branches_url: 'https://api.github.com/repos/facebook/react-native/branches{/branch}',
      tags_url: 'https://api.github.com/repos/facebook/react-native/tags',
      blobs_url: 'https://api.github.com/repos/facebook/react-native/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/facebook/react-native/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/facebook/react-native/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/facebook/react-native/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/facebook/react-native/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/facebook/react-native/languages',
      stargazers_url: 'https://api.github.com/repos/facebook/react-native/stargazers',
      contributors_url: 'https://api.github.com/repos/facebook/react-native/contributors',
      subscribers_url: 'https://api.github.com/repos/facebook/react-native/subscribers',
      subscription_url: 'https://api.github.com/repos/facebook/react-native/subscription',
      commits_url: 'https://api.github.com/repos/facebook/react-native/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/facebook/react-native/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/facebook/react-native/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/facebook/react-native/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/facebook/react-native/contents/{+path}',
      compare_url: 'https://api.github.com/repos/facebook/react-native/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/facebook/react-native/merges',
      archive_url: 'https://api.github.com/repos/facebook/react-native/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/facebook/react-native/downloads',
      issues_url: 'https://api.github.com/repos/facebook/react-native/issues{/number}',
      pulls_url: 'https://api.github.com/repos/facebook/react-native/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/facebook/react-native/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/facebook/react-native/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/facebook/react-native/labels{/name}',
      releases_url: 'https://api.github.com/repos/facebook/react-native/releases{/id}',
      deployments_url: 'https://api.github.com/repos/facebook/react-native/deployments',
      created_at: '2015-01-09T18:10:16Z',
      updated_at: '2020-06-21T17:02:36Z',
      pushed_at: '2020-06-21T03:24:45Z',
      git_url: 'git://github.com/facebook/react-native.git',
      ssh_url: 'git@github.com:facebook/react-native.git',
      clone_url: 'https://github.com/facebook/react-native.git',
      svn_url: 'https://github.com/facebook/react-native',
      homepage: 'https://reactnative.dev',
      size: 535060,
      stargazers_count: 88150,
      watchers_count: 88150,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 19568,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 944,
      license: {
        key: 'other',
        name: 'Other',
        spdx_id: 'NOASSERTION',
        url: null,
        node_id: 'MDc6TGljZW5zZTA=',
      },
      forks: 19568,
      open_issues: 944,
      watchers: 88150,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 63537249,
      node_id: 'MDEwOlJlcG9zaXRvcnk2MzUzNzI0OQ==',
      name: 'create-react-app',
      full_name: 'facebook/create-react-app',
      private: false,
      owner: {
        login: 'facebook',
        id: 69631,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
        avatar_url: 'https://avatars3.githubusercontent.com/u/69631?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/facebook',
        html_url: 'https://github.com/facebook',
        followers_url: 'https://api.github.com/users/facebook/followers',
        following_url: 'https://api.github.com/users/facebook/following{/other_user}',
        gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
        organizations_url: 'https://api.github.com/users/facebook/orgs',
        repos_url: 'https://api.github.com/users/facebook/repos',
        events_url: 'https://api.github.com/users/facebook/events{/privacy}',
        received_events_url: 'https://api.github.com/users/facebook/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/facebook/create-react-app',
      description: 'Set up a modern web app by running one command.',
      fork: false,
      url: 'https://api.github.com/repos/facebook/create-react-app',
      forks_url: 'https://api.github.com/repos/facebook/create-react-app/forks',
      keys_url: 'https://api.github.com/repos/facebook/create-react-app/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/facebook/create-react-app/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/facebook/create-react-app/teams',
      hooks_url: 'https://api.github.com/repos/facebook/create-react-app/hooks',
      issue_events_url:
        'https://api.github.com/repos/facebook/create-react-app/issues/events{/number}',
      events_url: 'https://api.github.com/repos/facebook/create-react-app/events',
      assignees_url: 'https://api.github.com/repos/facebook/create-react-app/assignees{/user}',
      branches_url: 'https://api.github.com/repos/facebook/create-react-app/branches{/branch}',
      tags_url: 'https://api.github.com/repos/facebook/create-react-app/tags',
      blobs_url: 'https://api.github.com/repos/facebook/create-react-app/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/facebook/create-react-app/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/facebook/create-react-app/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/facebook/create-react-app/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/facebook/create-react-app/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/facebook/create-react-app/languages',
      stargazers_url: 'https://api.github.com/repos/facebook/create-react-app/stargazers',
      contributors_url: 'https://api.github.com/repos/facebook/create-react-app/contributors',
      subscribers_url: 'https://api.github.com/repos/facebook/create-react-app/subscribers',
      subscription_url: 'https://api.github.com/repos/facebook/create-react-app/subscription',
      commits_url: 'https://api.github.com/repos/facebook/create-react-app/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/facebook/create-react-app/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/facebook/create-react-app/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/facebook/create-react-app/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/facebook/create-react-app/contents/{+path}',
      compare_url: 'https://api.github.com/repos/facebook/create-react-app/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/facebook/create-react-app/merges',
      archive_url: 'https://api.github.com/repos/facebook/create-react-app/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/facebook/create-react-app/downloads',
      issues_url: 'https://api.github.com/repos/facebook/create-react-app/issues{/number}',
      pulls_url: 'https://api.github.com/repos/facebook/create-react-app/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/facebook/create-react-app/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/facebook/create-react-app/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/facebook/create-react-app/labels{/name}',
      releases_url: 'https://api.github.com/repos/facebook/create-react-app/releases{/id}',
      deployments_url: 'https://api.github.com/repos/facebook/create-react-app/deployments',
      created_at: '2016-07-17T14:55:11Z',
      updated_at: '2020-06-21T20:05:18Z',
      pushed_at: '2020-06-20T20:27:06Z',
      git_url: 'git://github.com/facebook/create-react-app.git',
      ssh_url: 'git@github.com:facebook/create-react-app.git',
      clone_url: 'https://github.com/facebook/create-react-app.git',
      svn_url: 'https://github.com/facebook/create-react-app',
      homepage: 'https://create-react-app.dev',
      size: 13980,
      stargazers_count: 79656,
      watchers_count: 79656,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: true,
      forks_count: 19267,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 608,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 19267,
      open_issues: 608,
      watchers: 79656,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 19872456,
      node_id: 'MDEwOlJlcG9zaXRvcnkxOTg3MjQ1Ng==',
      name: 'react-router',
      full_name: 'ReactTraining/react-router',
      private: false,
      owner: {
        login: 'ReactTraining',
        id: 11823761,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjExODIzNzYx',
        avatar_url: 'https://avatars1.githubusercontent.com/u/11823761?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/ReactTraining',
        html_url: 'https://github.com/ReactTraining',
        followers_url: 'https://api.github.com/users/ReactTraining/followers',
        following_url: 'https://api.github.com/users/ReactTraining/following{/other_user}',
        gists_url: 'https://api.github.com/users/ReactTraining/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ReactTraining/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ReactTraining/subscriptions',
        organizations_url: 'https://api.github.com/users/ReactTraining/orgs',
        repos_url: 'https://api.github.com/users/ReactTraining/repos',
        events_url: 'https://api.github.com/users/ReactTraining/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ReactTraining/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/ReactTraining/react-router',
      description: 'Declarative routing for React',
      fork: false,
      url: 'https://api.github.com/repos/ReactTraining/react-router',
      forks_url: 'https://api.github.com/repos/ReactTraining/react-router/forks',
      keys_url: 'https://api.github.com/repos/ReactTraining/react-router/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/ReactTraining/react-router/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/ReactTraining/react-router/teams',
      hooks_url: 'https://api.github.com/repos/ReactTraining/react-router/hooks',
      issue_events_url:
        'https://api.github.com/repos/ReactTraining/react-router/issues/events{/number}',
      events_url: 'https://api.github.com/repos/ReactTraining/react-router/events',
      assignees_url: 'https://api.github.com/repos/ReactTraining/react-router/assignees{/user}',
      branches_url: 'https://api.github.com/repos/ReactTraining/react-router/branches{/branch}',
      tags_url: 'https://api.github.com/repos/ReactTraining/react-router/tags',
      blobs_url: 'https://api.github.com/repos/ReactTraining/react-router/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/ReactTraining/react-router/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/ReactTraining/react-router/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/ReactTraining/react-router/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/ReactTraining/react-router/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/ReactTraining/react-router/languages',
      stargazers_url: 'https://api.github.com/repos/ReactTraining/react-router/stargazers',
      contributors_url: 'https://api.github.com/repos/ReactTraining/react-router/contributors',
      subscribers_url: 'https://api.github.com/repos/ReactTraining/react-router/subscribers',
      subscription_url: 'https://api.github.com/repos/ReactTraining/react-router/subscription',
      commits_url: 'https://api.github.com/repos/ReactTraining/react-router/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/ReactTraining/react-router/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/ReactTraining/react-router/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/ReactTraining/react-router/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/ReactTraining/react-router/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/ReactTraining/react-router/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/ReactTraining/react-router/merges',
      archive_url: 'https://api.github.com/repos/ReactTraining/react-router/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/ReactTraining/react-router/downloads',
      issues_url: 'https://api.github.com/repos/ReactTraining/react-router/issues{/number}',
      pulls_url: 'https://api.github.com/repos/ReactTraining/react-router/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/ReactTraining/react-router/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/ReactTraining/react-router/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/ReactTraining/react-router/labels{/name}',
      releases_url: 'https://api.github.com/repos/ReactTraining/react-router/releases{/id}',
      deployments_url: 'https://api.github.com/repos/ReactTraining/react-router/deployments',
      created_at: '2014-05-16T22:22:51Z',
      updated_at: '2020-06-21T18:48:10Z',
      pushed_at: '2020-06-21T18:58:23Z',
      git_url: 'git://github.com/ReactTraining/react-router.git',
      ssh_url: 'git@github.com:ReactTraining/react-router.git',
      clone_url: 'https://github.com/ReactTraining/react-router.git',
      svn_url: 'https://github.com/ReactTraining/react-router',
      homepage: 'https://reacttraining.com/react-router/',
      size: 15163,
      stargazers_count: 40902,
      watchers_count: 40902,
      language: 'JavaScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      forks_count: 8172,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 58,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 8172,
      open_issues: 58,
      watchers: 40902,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 22670857,
      node_id: 'MDEwOlJlcG9zaXRvcnkyMjY3MDg1Nw==',
      name: 'awesome-react',
      full_name: 'enaqx/awesome-react',
      private: false,
      owner: {
        login: 'enaqx',
        id: 182219,
        node_id: 'MDQ6VXNlcjE4MjIxOQ==',
        avatar_url: 'https://avatars1.githubusercontent.com/u/182219?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/enaqx',
        html_url: 'https://github.com/enaqx',
        followers_url: 'https://api.github.com/users/enaqx/followers',
        following_url: 'https://api.github.com/users/enaqx/following{/other_user}',
        gists_url: 'https://api.github.com/users/enaqx/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/enaqx/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/enaqx/subscriptions',
        organizations_url: 'https://api.github.com/users/enaqx/orgs',
        repos_url: 'https://api.github.com/users/enaqx/repos',
        events_url: 'https://api.github.com/users/enaqx/events{/privacy}',
        received_events_url: 'https://api.github.com/users/enaqx/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/enaqx/awesome-react',
      description: 'A collection of awesome things regarding React ecosystem',
      fork: false,
      url: 'https://api.github.com/repos/enaqx/awesome-react',
      forks_url: 'https://api.github.com/repos/enaqx/awesome-react/forks',
      keys_url: 'https://api.github.com/repos/enaqx/awesome-react/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/enaqx/awesome-react/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/enaqx/awesome-react/teams',
      hooks_url: 'https://api.github.com/repos/enaqx/awesome-react/hooks',
      issue_events_url: 'https://api.github.com/repos/enaqx/awesome-react/issues/events{/number}',
      events_url: 'https://api.github.com/repos/enaqx/awesome-react/events',
      assignees_url: 'https://api.github.com/repos/enaqx/awesome-react/assignees{/user}',
      branches_url: 'https://api.github.com/repos/enaqx/awesome-react/branches{/branch}',
      tags_url: 'https://api.github.com/repos/enaqx/awesome-react/tags',
      blobs_url: 'https://api.github.com/repos/enaqx/awesome-react/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/enaqx/awesome-react/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/enaqx/awesome-react/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/enaqx/awesome-react/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/enaqx/awesome-react/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/enaqx/awesome-react/languages',
      stargazers_url: 'https://api.github.com/repos/enaqx/awesome-react/stargazers',
      contributors_url: 'https://api.github.com/repos/enaqx/awesome-react/contributors',
      subscribers_url: 'https://api.github.com/repos/enaqx/awesome-react/subscribers',
      subscription_url: 'https://api.github.com/repos/enaqx/awesome-react/subscription',
      commits_url: 'https://api.github.com/repos/enaqx/awesome-react/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/enaqx/awesome-react/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/enaqx/awesome-react/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/enaqx/awesome-react/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/enaqx/awesome-react/contents/{+path}',
      compare_url: 'https://api.github.com/repos/enaqx/awesome-react/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/enaqx/awesome-react/merges',
      archive_url: 'https://api.github.com/repos/enaqx/awesome-react/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/enaqx/awesome-react/downloads',
      issues_url: 'https://api.github.com/repos/enaqx/awesome-react/issues{/number}',
      pulls_url: 'https://api.github.com/repos/enaqx/awesome-react/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/enaqx/awesome-react/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/enaqx/awesome-react/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/enaqx/awesome-react/labels{/name}',
      releases_url: 'https://api.github.com/repos/enaqx/awesome-react/releases{/id}',
      deployments_url: 'https://api.github.com/repos/enaqx/awesome-react/deployments',
      created_at: '2014-08-06T05:31:44Z',
      updated_at: '2020-06-21T20:40:19Z',
      pushed_at: '2020-06-21T10:53:37Z',
      git_url: 'git://github.com/enaqx/awesome-react.git',
      ssh_url: 'git@github.com:enaqx/awesome-react.git',
      clone_url: 'https://github.com/enaqx/awesome-react.git',
      svn_url: 'https://github.com/enaqx/awesome-react',
      homepage: '',
      size: 2312,
      stargazers_count: 37394,
      watchers_count: 37394,
      language: null,
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      forks_count: 4444,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 57,
      license: null,
      forks: 4444,
      open_issues: 57,
      watchers: 37394,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 32948863,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMjk0ODg2Mw==',
      name: 'awesome-react-native',
      full_name: 'jondot/awesome-react-native',
      private: false,
      owner: {
        login: 'jondot',
        id: 83390,
        node_id: 'MDQ6VXNlcjgzMzkw',
        avatar_url: 'https://avatars0.githubusercontent.com/u/83390?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/jondot',
        html_url: 'https://github.com/jondot',
        followers_url: 'https://api.github.com/users/jondot/followers',
        following_url: 'https://api.github.com/users/jondot/following{/other_user}',
        gists_url: 'https://api.github.com/users/jondot/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/jondot/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/jondot/subscriptions',
        organizations_url: 'https://api.github.com/users/jondot/orgs',
        repos_url: 'https://api.github.com/users/jondot/repos',
        events_url: 'https://api.github.com/users/jondot/events{/privacy}',
        received_events_url: 'https://api.github.com/users/jondot/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/jondot/awesome-react-native',
      description: 'Awesome React Native components, news, tools, and learning material!',
      fork: false,
      url: 'https://api.github.com/repos/jondot/awesome-react-native',
      forks_url: 'https://api.github.com/repos/jondot/awesome-react-native/forks',
      keys_url: 'https://api.github.com/repos/jondot/awesome-react-native/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/jondot/awesome-react-native/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/jondot/awesome-react-native/teams',
      hooks_url: 'https://api.github.com/repos/jondot/awesome-react-native/hooks',
      issue_events_url:
        'https://api.github.com/repos/jondot/awesome-react-native/issues/events{/number}',
      events_url: 'https://api.github.com/repos/jondot/awesome-react-native/events',
      assignees_url: 'https://api.github.com/repos/jondot/awesome-react-native/assignees{/user}',
      branches_url: 'https://api.github.com/repos/jondot/awesome-react-native/branches{/branch}',
      tags_url: 'https://api.github.com/repos/jondot/awesome-react-native/tags',
      blobs_url: 'https://api.github.com/repos/jondot/awesome-react-native/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/jondot/awesome-react-native/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/jondot/awesome-react-native/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/jondot/awesome-react-native/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/jondot/awesome-react-native/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/jondot/awesome-react-native/languages',
      stargazers_url: 'https://api.github.com/repos/jondot/awesome-react-native/stargazers',
      contributors_url: 'https://api.github.com/repos/jondot/awesome-react-native/contributors',
      subscribers_url: 'https://api.github.com/repos/jondot/awesome-react-native/subscribers',
      subscription_url: 'https://api.github.com/repos/jondot/awesome-react-native/subscription',
      commits_url: 'https://api.github.com/repos/jondot/awesome-react-native/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/jondot/awesome-react-native/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/jondot/awesome-react-native/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/jondot/awesome-react-native/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/jondot/awesome-react-native/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/jondot/awesome-react-native/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/jondot/awesome-react-native/merges',
      archive_url:
        'https://api.github.com/repos/jondot/awesome-react-native/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/jondot/awesome-react-native/downloads',
      issues_url: 'https://api.github.com/repos/jondot/awesome-react-native/issues{/number}',
      pulls_url: 'https://api.github.com/repos/jondot/awesome-react-native/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/jondot/awesome-react-native/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/jondot/awesome-react-native/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/jondot/awesome-react-native/labels{/name}',
      releases_url: 'https://api.github.com/repos/jondot/awesome-react-native/releases{/id}',
      deployments_url: 'https://api.github.com/repos/jondot/awesome-react-native/deployments',
      created_at: '2015-03-26T19:58:06Z',
      updated_at: '2020-06-21T20:30:20Z',
      pushed_at: '2020-06-15T23:25:03Z',
      git_url: 'git://github.com/jondot/awesome-react-native.git',
      ssh_url: 'git@github.com:jondot/awesome-react-native.git',
      clone_url: 'https://github.com/jondot/awesome-react-native.git',
      svn_url: 'https://github.com/jondot/awesome-react-native',
      homepage: 'http://www.awesome-react-native.com',
      size: 5218,
      stargazers_count: 27423,
      watchers_count: 27423,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 3404,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 36,
      license: null,
      forks: 3404,
      open_issues: 36,
      watchers: 27423,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 30969188,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMDk2OTE4OA==',
      name: 'react-boilerplate',
      full_name: 'react-boilerplate/react-boilerplate',
      private: false,
      owner: {
        login: 'react-boilerplate',
        id: 25323389,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjI1MzIzMzg5',
        avatar_url: 'https://avatars2.githubusercontent.com/u/25323389?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/react-boilerplate',
        html_url: 'https://github.com/react-boilerplate',
        followers_url: 'https://api.github.com/users/react-boilerplate/followers',
        following_url: 'https://api.github.com/users/react-boilerplate/following{/other_user}',
        gists_url: 'https://api.github.com/users/react-boilerplate/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/react-boilerplate/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/react-boilerplate/subscriptions',
        organizations_url: 'https://api.github.com/users/react-boilerplate/orgs',
        repos_url: 'https://api.github.com/users/react-boilerplate/repos',
        events_url: 'https://api.github.com/users/react-boilerplate/events{/privacy}',
        received_events_url: 'https://api.github.com/users/react-boilerplate/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/react-boilerplate/react-boilerplate',
      description:
        ':fire: A highly scalable, offline-first foundation with the best developer experience and a focus on performance and best practices.',
      fork: false,
      url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate',
      forks_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/forks',
      keys_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/teams',
      hooks_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/hooks',
      issue_events_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/issues/events{/number}',
      events_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/events',
      assignees_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/assignees{/user}',
      branches_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/branches{/branch}',
      tags_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/tags',
      blobs_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/git/blobs{/sha}',
      git_tags_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/git/tags{/sha}',
      git_refs_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/git/trees{/sha}',
      statuses_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/languages',
      stargazers_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/stargazers',
      contributors_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/contributors',
      subscribers_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/subscribers',
      subscription_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/subscription',
      commits_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/commits{/sha}',
      git_commits_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/git/commits{/sha}',
      comments_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/issues/comments{/number}',
      contents_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/merges',
      archive_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/downloads',
      issues_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/issues{/number}',
      pulls_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/react-boilerplate/react-boilerplate/labels{/name}',
      releases_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/releases{/id}',
      deployments_url:
        'https://api.github.com/repos/react-boilerplate/react-boilerplate/deployments',
      created_at: '2015-02-18T14:36:32Z',
      updated_at: '2020-06-21T20:22:36Z',
      pushed_at: '2020-06-19T11:48:45Z',
      git_url: 'git://github.com/react-boilerplate/react-boilerplate.git',
      ssh_url: 'git@github.com:react-boilerplate/react-boilerplate.git',
      clone_url: 'https://github.com/react-boilerplate/react-boilerplate.git',
      svn_url: 'https://github.com/react-boilerplate/react-boilerplate',
      homepage: 'https://www.reactboilerplate.com',
      size: 8166,
      stargazers_count: 25701,
      watchers_count: 25701,
      language: 'JavaScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      forks_count: 5345,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 49,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 5345,
      open_issues: 49,
      watchers: 25701,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 61893399,
      node_id: 'MDEwOlJlcG9zaXRvcnk2MTg5MzM5OQ==',
      name: 'awesome-react-components',
      full_name: 'brillout/awesome-react-components',
      private: false,
      owner: {
        login: 'brillout',
        id: 1005638,
        node_id: 'MDQ6VXNlcjEwMDU2Mzg=',
        avatar_url: 'https://avatars2.githubusercontent.com/u/1005638?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/brillout',
        html_url: 'https://github.com/brillout',
        followers_url: 'https://api.github.com/users/brillout/followers',
        following_url: 'https://api.github.com/users/brillout/following{/other_user}',
        gists_url: 'https://api.github.com/users/brillout/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/brillout/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/brillout/subscriptions',
        organizations_url: 'https://api.github.com/users/brillout/orgs',
        repos_url: 'https://api.github.com/users/brillout/repos',
        events_url: 'https://api.github.com/users/brillout/events{/privacy}',
        received_events_url: 'https://api.github.com/users/brillout/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/brillout/awesome-react-components',
      description: 'Curated List of React Components & Libraries.',
      fork: false,
      url: 'https://api.github.com/repos/brillout/awesome-react-components',
      forks_url: 'https://api.github.com/repos/brillout/awesome-react-components/forks',
      keys_url: 'https://api.github.com/repos/brillout/awesome-react-components/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/brillout/awesome-react-components/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/brillout/awesome-react-components/teams',
      hooks_url: 'https://api.github.com/repos/brillout/awesome-react-components/hooks',
      issue_events_url:
        'https://api.github.com/repos/brillout/awesome-react-components/issues/events{/number}',
      events_url: 'https://api.github.com/repos/brillout/awesome-react-components/events',
      assignees_url:
        'https://api.github.com/repos/brillout/awesome-react-components/assignees{/user}',
      branches_url:
        'https://api.github.com/repos/brillout/awesome-react-components/branches{/branch}',
      tags_url: 'https://api.github.com/repos/brillout/awesome-react-components/tags',
      blobs_url: 'https://api.github.com/repos/brillout/awesome-react-components/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/brillout/awesome-react-components/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/brillout/awesome-react-components/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/brillout/awesome-react-components/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/brillout/awesome-react-components/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/brillout/awesome-react-components/languages',
      stargazers_url: 'https://api.github.com/repos/brillout/awesome-react-components/stargazers',
      contributors_url:
        'https://api.github.com/repos/brillout/awesome-react-components/contributors',
      subscribers_url: 'https://api.github.com/repos/brillout/awesome-react-components/subscribers',
      subscription_url:
        'https://api.github.com/repos/brillout/awesome-react-components/subscription',
      commits_url: 'https://api.github.com/repos/brillout/awesome-react-components/commits{/sha}',
      git_commits_url:
        'https://api.github.com/repos/brillout/awesome-react-components/git/commits{/sha}',
      comments_url:
        'https://api.github.com/repos/brillout/awesome-react-components/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/brillout/awesome-react-components/issues/comments{/number}',
      contents_url:
        'https://api.github.com/repos/brillout/awesome-react-components/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/brillout/awesome-react-components/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/brillout/awesome-react-components/merges',
      archive_url:
        'https://api.github.com/repos/brillout/awesome-react-components/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/brillout/awesome-react-components/downloads',
      issues_url: 'https://api.github.com/repos/brillout/awesome-react-components/issues{/number}',
      pulls_url: 'https://api.github.com/repos/brillout/awesome-react-components/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/brillout/awesome-react-components/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/brillout/awesome-react-components/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/brillout/awesome-react-components/labels{/name}',
      releases_url: 'https://api.github.com/repos/brillout/awesome-react-components/releases{/id}',
      deployments_url: 'https://api.github.com/repos/brillout/awesome-react-components/deployments',
      created_at: '2016-06-24T15:19:33Z',
      updated_at: '2020-06-21T18:30:21Z',
      pushed_at: '2020-06-21T02:49:42Z',
      git_url: 'git://github.com/brillout/awesome-react-components.git',
      ssh_url: 'git@github.com:brillout/awesome-react-components.git',
      clone_url: 'https://github.com/brillout/awesome-react-components.git',
      svn_url: 'https://github.com/brillout/awesome-react-components',
      homepage: '',
      size: 818,
      stargazers_count: 22868,
      watchers_count: 22868,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 1847,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: 'cc0-1.0',
        name: 'Creative Commons Zero v1.0 Universal',
        spdx_id: 'CC0-1.0',
        url: 'https://api.github.com/licenses/cc0-1.0',
        node_id: 'MDc6TGljZW5zZTY=',
      },
      forks: 1847,
      open_issues: 0,
      watchers: 22868,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 23338716,
      node_id: 'MDEwOlJlcG9zaXRvcnkyMzMzODcxNg==',
      name: 'react-select',
      full_name: 'JedWatson/react-select',
      private: false,
      owner: {
        login: 'JedWatson',
        id: 872310,
        node_id: 'MDQ6VXNlcjg3MjMxMA==',
        avatar_url: 'https://avatars3.githubusercontent.com/u/872310?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/JedWatson',
        html_url: 'https://github.com/JedWatson',
        followers_url: 'https://api.github.com/users/JedWatson/followers',
        following_url: 'https://api.github.com/users/JedWatson/following{/other_user}',
        gists_url: 'https://api.github.com/users/JedWatson/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/JedWatson/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/JedWatson/subscriptions',
        organizations_url: 'https://api.github.com/users/JedWatson/orgs',
        repos_url: 'https://api.github.com/users/JedWatson/repos',
        events_url: 'https://api.github.com/users/JedWatson/events{/privacy}',
        received_events_url: 'https://api.github.com/users/JedWatson/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/JedWatson/react-select',
      description: 'The Select Component for React.js',
      fork: false,
      url: 'https://api.github.com/repos/JedWatson/react-select',
      forks_url: 'https://api.github.com/repos/JedWatson/react-select/forks',
      keys_url: 'https://api.github.com/repos/JedWatson/react-select/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/JedWatson/react-select/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/JedWatson/react-select/teams',
      hooks_url: 'https://api.github.com/repos/JedWatson/react-select/hooks',
      issue_events_url:
        'https://api.github.com/repos/JedWatson/react-select/issues/events{/number}',
      events_url: 'https://api.github.com/repos/JedWatson/react-select/events',
      assignees_url: 'https://api.github.com/repos/JedWatson/react-select/assignees{/user}',
      branches_url: 'https://api.github.com/repos/JedWatson/react-select/branches{/branch}',
      tags_url: 'https://api.github.com/repos/JedWatson/react-select/tags',
      blobs_url: 'https://api.github.com/repos/JedWatson/react-select/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/JedWatson/react-select/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/JedWatson/react-select/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/JedWatson/react-select/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/JedWatson/react-select/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/JedWatson/react-select/languages',
      stargazers_url: 'https://api.github.com/repos/JedWatson/react-select/stargazers',
      contributors_url: 'https://api.github.com/repos/JedWatson/react-select/contributors',
      subscribers_url: 'https://api.github.com/repos/JedWatson/react-select/subscribers',
      subscription_url: 'https://api.github.com/repos/JedWatson/react-select/subscription',
      commits_url: 'https://api.github.com/repos/JedWatson/react-select/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/JedWatson/react-select/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/JedWatson/react-select/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/JedWatson/react-select/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/JedWatson/react-select/contents/{+path}',
      compare_url: 'https://api.github.com/repos/JedWatson/react-select/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/JedWatson/react-select/merges',
      archive_url: 'https://api.github.com/repos/JedWatson/react-select/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/JedWatson/react-select/downloads',
      issues_url: 'https://api.github.com/repos/JedWatson/react-select/issues{/number}',
      pulls_url: 'https://api.github.com/repos/JedWatson/react-select/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/JedWatson/react-select/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/JedWatson/react-select/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/JedWatson/react-select/labels{/name}',
      releases_url: 'https://api.github.com/repos/JedWatson/react-select/releases{/id}',
      deployments_url: 'https://api.github.com/repos/JedWatson/react-select/deployments',
      created_at: '2014-08-26T04:27:45Z',
      updated_at: '2020-06-21T18:28:43Z',
      pushed_at: '2020-06-16T10:59:48Z',
      git_url: 'git://github.com/JedWatson/react-select.git',
      ssh_url: 'git@github.com:JedWatson/react-select.git',
      clone_url: 'https://github.com/JedWatson/react-select.git',
      svn_url: 'https://github.com/JedWatson/react-select',
      homepage: 'https://react-select.com/',
      size: 15779,
      stargazers_count: 20308,
      watchers_count: 20308,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      forks_count: 3518,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 356,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 3518,
      open_issues: 356,
      watchers: 20308,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 18840003,
      node_id: 'MDEwOlJlcG9zaXRvcnkxODg0MDAwMw==',
      name: 'react-starter-kit',
      full_name: 'kriasoft/react-starter-kit',
      private: false,
      owner: {
        login: 'kriasoft',
        id: 773036,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjc3MzAzNg==',
        avatar_url: 'https://avatars2.githubusercontent.com/u/773036?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/kriasoft',
        html_url: 'https://github.com/kriasoft',
        followers_url: 'https://api.github.com/users/kriasoft/followers',
        following_url: 'https://api.github.com/users/kriasoft/following{/other_user}',
        gists_url: 'https://api.github.com/users/kriasoft/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/kriasoft/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/kriasoft/subscriptions',
        organizations_url: 'https://api.github.com/users/kriasoft/orgs',
        repos_url: 'https://api.github.com/users/kriasoft/repos',
        events_url: 'https://api.github.com/users/kriasoft/events{/privacy}',
        received_events_url: 'https://api.github.com/users/kriasoft/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/kriasoft/react-starter-kit',
      description:
        'React Starter Kit — isomorphic web app boilerplate (Node.js, Express, GraphQL, React.js, Babel, PostCSS, Webpack, Browsersync)',
      fork: false,
      url: 'https://api.github.com/repos/kriasoft/react-starter-kit',
      forks_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/forks',
      keys_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/kriasoft/react-starter-kit/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/teams',
      hooks_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/hooks',
      issue_events_url:
        'https://api.github.com/repos/kriasoft/react-starter-kit/issues/events{/number}',
      events_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/events',
      assignees_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/assignees{/user}',
      branches_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/branches{/branch}',
      tags_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/tags',
      blobs_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/languages',
      stargazers_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/stargazers',
      contributors_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/contributors',
      subscribers_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/subscribers',
      subscription_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/subscription',
      commits_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/kriasoft/react-starter-kit/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/kriasoft/react-starter-kit/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/merges',
      archive_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/downloads',
      issues_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/issues{/number}',
      pulls_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/kriasoft/react-starter-kit/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/labels{/name}',
      releases_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/releases{/id}',
      deployments_url: 'https://api.github.com/repos/kriasoft/react-starter-kit/deployments',
      created_at: '2014-04-16T13:08:18Z',
      updated_at: '2020-06-21T20:40:16Z',
      pushed_at: '2020-06-15T03:36:52Z',
      git_url: 'git://github.com/kriasoft/react-starter-kit.git',
      ssh_url: 'git@github.com:kriasoft/react-starter-kit.git',
      clone_url: 'https://github.com/kriasoft/react-starter-kit.git',
      svn_url: 'https://github.com/kriasoft/react-starter-kit',
      homepage: 'https://reactstarter.com',
      size: 8885,
      stargazers_count: 20158,
      watchers_count: 20158,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 3976,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 494,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      forks: 3976,
      open_issues: 494,
      watchers: 20158,
      default_branch: 'master',
      score: 1,
    },
  ],
};
